# generated by tools/build_showcase.py - do not edit
# scene: machine_hall. See docs/showcase_spec.md.

gamerule advance_time false
gamerule advance_weather false
time set noon
weather clear

# Scoped by type and distance so re-running replaces this scene's paintings rather than
# hanging a second set on top of the first.
kill @e[type=minecraft:painting,distance=..64]

fill ~-4 ~-1 ~-4 ~21 ~9 ~17 air

place template recompile:showcase/machine_hall ~0 ~-1 ~0

# recompile:separator: components placed, then assembled by the game
setblock ~8 ~0 ~5 recompile:machine_frame
setblock ~9 ~0 ~5 recompile:machine_frame
setblock ~7 ~0 ~6 recompile:machine_frame
setblock ~8 ~0 ~6 recompile:machine_frame
setblock ~9 ~0 ~6 recompile:machine_frame
setblock ~7 ~1 ~5 recompile:machine_frame
setblock ~7 ~1 ~6 recompile:machine_frame
setblock ~8 ~1 ~5 recompile:steel_i_beam
setblock ~8 ~1 ~6 recompile:steel_i_beam
setblock ~9 ~1 ~5 recompile:steel_i_beam
setblock ~9 ~1 ~6 recompile:steel_i_beam
setblock ~7 ~0 ~5 recompile:separator[facing=north]
setblock ~8 ~0 ~5 minecraft:air
setblock ~8 ~0 ~5 recompile:machine_frame


tp @s ~8.5 ~1.8 ~14 180.0 5.0
