# generated by tools/build_showcase.py - do not edit
# scene: machine_wall. See docs/showcase_spec.md.

gamerule advance_time false
gamerule advance_weather false
time set noon
weather clear

# Scoped by type and distance so re-running replaces this scene's paintings rather than
# hanging a second set on top of the first.
kill @e[type=minecraft:painting,distance=..64]

fill ~-4 ~-1 ~-4 ~17 ~17 ~12 air

place template recompile:showcase/machine_wall ~0 ~-1 ~0

# recompile:separator: components placed, then assembled by the game
setblock ~6 ~0 ~1 recompile:machine_frame
setblock ~7 ~0 ~1 recompile:machine_frame
setblock ~5 ~0 ~2 recompile:machine_frame
setblock ~6 ~0 ~2 recompile:machine_frame
setblock ~7 ~0 ~2 recompile:machine_frame
setblock ~5 ~1 ~1 recompile:machine_frame
setblock ~5 ~1 ~2 recompile:machine_frame
setblock ~6 ~1 ~1 recompile:steel_i_beam
setblock ~6 ~1 ~2 recompile:steel_i_beam
setblock ~7 ~1 ~1 recompile:steel_i_beam
setblock ~7 ~1 ~2 recompile:steel_i_beam
setblock ~5 ~0 ~1 recompile:separator[facing=north]
setblock ~6 ~0 ~1 minecraft:air
setblock ~6 ~0 ~1 recompile:machine_frame


tp @s ~6.5 ~4.4 ~10 180.0 2.0
