# generated by tools/build_showcase.py - do not edit
# scene: museum. See docs/showcase_spec.md.

gamerule doDaylightCycle false
gamerule doWeatherCycle false
time set noon
weather clear

# Scoped by type and distance so re-running replaces this scene's paintings rather than
# hanging a second set on top of the first.
kill @e[type=minecraft:painting,distance=..64]

place template recompile:showcase/museum 0 64 0

summon minecraft:painting 2 67 1 {facing:0b, variant:"recompile:pearl_earring"}
summon minecraft:painting 6 67 1 {facing:0b, variant:"recompile:the_scream"}
summon minecraft:painting 10 66 1 {facing:0b, variant:"recompile:la_grande_jatte"}
summon minecraft:painting 2 72 1 {facing:0b, variant:"recompile:starry_night"}
summon minecraft:painting 6 72 1 {facing:0b, variant:"recompile:mona_lisa"}
summon minecraft:painting 10 71 1 {facing:0b, variant:"recompile:great_wave"}

tp @s 6.5 69.5 14.5 180.0 0.0
