# generated by tools/build_showcase.py - do not edit
# scene: reclaim_after. See docs/showcase_spec.md.

gamerule advance_time false
gamerule advance_weather false
time set noon
weather clear

# Scoped by type and distance so re-running replaces this scene's paintings rather than
# hanging a second set on top of the first.
kill @e[type=minecraft:painting,distance=..64]

fill ~0 ~-1 ~0 ~21 ~14 ~28 air

place template recompile:showcase/reclaim_after ~0 ~-1 ~0


tp @s ~10.5 ~1.6 ~26 180.0 4.0
