# generated by tools/build_showcase.py - do not edit
# scene: reclaim_after. See docs/showcase_spec.md.

gamerule advance_time false
gamerule advance_weather false
time set noon
weather clear

# Scoped by type and distance so re-running replaces this scene's paintings rather than
# hanging a second set on top of the first.
kill @e[type=minecraft:painting,distance=..64]

fill 200 120 200 221 135 219 air

place template recompile:showcase/reclaim_after 200 120 200


tp @s 210.5 127.0 227.0 180.0 18.0
