import json, os, sys, collections

from paths import WORK as SP, MCDATA as MC
idx = json.load(open(SP + "/index.json"))
wg = json.load(open(SP + "/worldgen.json"))
SB = json.load(open(SP + "/structblocks.json"))
src = idx["src"]
craft = set(idx["craftable"])
BD, BB, BM = wg["biome_domain"], wg["biome_blocks"], wg["biome_mobs"]

CODE = {
    "stronghold": ["stone_bricks", "mossy_stone_bricks", "cracked_stone_bricks", "chiseled_stone_bricks",
                   "infested_stone_bricks", "iron_bars", "bookshelf", "end_portal_frame", "oak_planks",
                   "oak_fence", "oak_door", "iron_door", "stone_button", "stone_brick_stairs",
                   "stone_brick_slab", "torch", "chest", "spawner", "water", "lava", "cobblestone",
                   "smooth_stone_slab", "ladder"],
    "mineshaft": ["oak_planks", "oak_fence", "dark_oak_planks", "dark_oak_fence", "rail", "powered_rail",
                  "detector_rail", "torch", "cobweb", "chest", "spawner", "oak_slab", "dark_oak_slab"],
    "ocean_monument": ["prismarine", "prismarine_bricks", "dark_prismarine", "sea_lantern", "wet_sponge",
                       "gold_block"],
    "nether_fortress": ["nether_bricks", "nether_brick_fence", "nether_brick_stairs", "spawner",
                        "nether_wart", "soul_sand", "chest", "lava"],
    "desert_pyramid": ["sandstone", "cut_sandstone", "chiseled_sandstone", "sandstone_stairs",
                       "sandstone_slab", "orange_terracotta", "blue_terracotta", "tnt",
                       "stone_pressure_plate", "chest"],
    "jungle_temple": ["cobblestone", "mossy_cobblestone", "chiseled_stone_bricks", "lever", "redstone_wire",
                      "sticky_piston", "tripwire", "tripwire_hook", "vine", "chest", "dispenser"],
    "swamp_hut": ["spruce_planks", "spruce_log", "spruce_fence", "spruce_stairs", "cauldron",
                  "crafting_table", "oak_fence", "flower_pot", "red_mushroom"],
}
STRUCT_BLOCKS = {k: set(v) for k, v in SB.items() if not k.endswith(".nbt")}
for k, v in CODE.items():
    STRUCT_BLOCKS[k] = {"minecraft:" + x for x in v}

SURF = collections.defaultdict(set)


def walkn(o, acc):
    if isinstance(o, dict):
        n = o.get("Name")
        if isinstance(n, str):
            acc.add(n)
        for v in o.values():
            walkn(v, acc)
    elif isinstance(o, list):
        for v in o:
            walkn(v, acc)


ND = MC + "/data/minecraft/worldgen/noise_settings"
for f in os.listdir(ND):
    acc = set()
    walkn(json.load(open(ND + "/" + f)), acc)
    SURF[f[:-5]] = acc

EXTRA = ["oak_log", "spruce_log", "birch_log", "jungle_log", "acacia_log", "dark_oak_log", "mangrove_log",
         "cherry_log", "pale_oak_log", "crimson_stem", "warped_stem", "bamboo", "sugar_cane", "cactus",
         "kelp", "seagrass", "vine", "glow_lichen", "snow", "ice", "clay", "gravel", "sand", "dirt",
         "pumpkin", "melon", "sweet_berry_bush", "cave_vines", "obsidian", "spawner", "cobweb",
         "turtle_egg", "frogspawn", "sea_pickle", "lily_pad", "dead_bush", "moss_block", "azalea",
         "flowering_azalea", "mud", "suspicious_sand", "suspicious_gravel", "amethyst_cluster",
         "budding_amethyst", "pointed_dripstone", "dripstone_block", "sculk", "sculk_vein",
         "sculk_catalyst", "sculk_sensor", "sculk_shrieker", "reinforced_deepslate", "bee_nest",
         "mangrove_roots", "muddy_mangrove_roots", "big_dripleaf", "small_dripleaf", "spore_blossom",
         "hanging_roots", "rooted_dirt", "nether_gold_ore", "nether_quartz_ore", "ancient_debris",
         "magma_block", "glowstone", "shroomlight", "crying_obsidian", "chorus_flower", "chorus_plant",
         "end_stone", "bedrock", "water", "lava", "tall_grass", "short_grass", "fern", "large_fern",
         "cocoa", "melon_stem", "pumpkin_stem", "moss_carpet", "pale_moss_block", "pale_hanging_moss",
         "creaking_heart", "leaf_litter", "wildflowers", "bush", "firefly_bush", "cactus_flower",
         "short_dry_grass", "tall_dry_grass", "dry_short_grass", "dry_tall_grass"]

# NATURAL = generated by terrain or a biome feature (as opposed to only inside a structure).
NATURAL = set()
for v in BB.values():
    NATURAL |= set(v)
for v in SURF.values():
    NATURAL |= v
NATURAL |= {"minecraft:" + x for x in EXTRA}

SURFACE_ITEMS = set()
for v in SURF.values():
    SURFACE_ITEMS |= v

WORLDGEN = set()
for v in BB.values():
    WORLDGEN |= set(v)
for v in STRUCT_BLOCKS.values():
    WORLDGEN |= v
for v in SURF.values():
    WORLDGEN |= v
WORLDGEN |= {"minecraft:" + x for x in EXTRA}

SDOM = {"bastion": "Nether", "nether_fossils": "Nether", "ruined_portal": "Nether",
        "nether_fortress": "Nether", "end_city": "End", "shipwreck": "Ocean",
        "underwater_ruin": "Ocean", "ocean_monument": "Ocean", "ancient_city": "Cave & Underground",
        "mineshaft": "Cave & Underground", "stronghold": "Cave & Underground",
        "fossil": "Cave & Underground", "desert_pyramid": "Desert", "jungle_temple": "Jungle",
        "swamp_hut": "Swamp"}

# Mobs that never appear in a biome spawner list (structure-spawned, built, bred, or summoned).
MOB_FALLBACK = {
    "blaze": "Nether", "wither_skeleton": "Nether", "piglin_brute": "Nether", "zoglin": "Nether",
    "guardian": "Ocean", "elder_guardian": "Ocean", "zombie_nautilus": "Ocean", "tadpole": "Swamp",
    "shulker": "End", "ender_dragon": "End", "endermite": "End",
    "warden": "Cave & Underground", "cave_spider": "Cave & Underground",
    "silverfish": "Cave & Underground",
    "breeze": "Structures & Chest Loot", "evoker": "Structures & Chest Loot",
    "vindicator": "Structures & Chest Loot", "pillager": "Structures & Chest Loot",
    "ravager": "Structures & Chest Loot", "vex": "Structures & Chest Loot",
    "allay": "Structures & Chest Loot", "illusioner": "Structures & Chest Loot",
    "villager": "Trading", "wandering_trader": "Trading", "trader_llama": "Trading",
    "sniffer": "Archaeology",
    "bee": "Overworld (other)", "cat": "Overworld (other)", "sheep": "Overworld (other)",
    "iron_golem": "Overworld (other)", "snow_golem": "Overworld (other)", "mule": "Overworld (other)",
    "skeleton_horse": "Overworld (other)", "phantom": "Overworld (other)", "wither": "Overworld (other)",
    "creaking": "Forest", "camel_husk": "Desert", "happy_ghast": "Nether",
    "copper_golem": "Overworld (other)", "armor_stand": "Overworld (other)",
    "player": "Overworld (other)", "giant": "Overworld (other)", "mannequin": "Overworld (other)",
}

blk_dom = collections.defaultdict(set)
mob_dom = collections.defaultdict(set)
for b, d in BD.items():
    for x in BB.get(b, []):
        blk_dom[x].add(d)
    for m in BM.get(b, []):
        mob_dom[m].add(d)
for s, bs in STRUCT_BLOCKS.items():
    for x in bs:
        blk_dom[x].add(SDOM.get(s, "Structures & Chest Loot"))
# Surface-rule blocks that are biome-characteristic rather than generic overworld terrain.
SURF_OVERRIDE = {}
for t in ("terracotta", "white_terracotta", "orange_terracotta", "yellow_terracotta",
          "brown_terracotta", "red_terracotta", "light_gray_terracotta", "red_sand", "red_sandstone"):
    SURF_OVERRIDE["minecraft:" + t] = "Badlands"
SURF_OVERRIDE["minecraft:mycelium"] = "Mushroom Fields"
SURF_OVERRIDE["minecraft:podzol"] = "Taiga"
for t in ("packed_ice", "blue_ice", "snow_block", "powder_snow", "ice", "snow"):
    SURF_OVERRIDE["minecraft:" + t] = "Snowy"
SURF_OVERRIDE["minecraft:mud"] = "Swamp"

for n, bs in SURF.items():
    d = {"nether": "Nether", "end": "End"}.get(n, "Overworld (other)")
    for x in bs:
        blk_dom[x].add(SURF_OVERRIDE.get(x, d) if d == "Overworld (other)" else d)

DOMS = ["Wood", "Cave & Underground", "Ocean", "River", "Beach", "Nether", "End", "Desert", "Badlands",
        "Jungle", "Savanna", "Taiga", "Forest", "Swamp", "Snowy", "Mushroom Fields", "Mountain",
        "Overworld (other)", "Structures & Chest Loot", "Trading", "Archaeology", "Fishing", "Other"]

# Overworld surface biomes. An item found across 3+ of these is generic, not biome-specific.
OW_BIOME = {"Desert", "Badlands", "Jungle", "Savanna", "Taiga", "Forest", "Swamp", "Snowy",
            "Mushroom Fields", "Mountain", "Beach", "River"}

# Filing the algorithm gets defensibly wrong (an item's full domain list is kept on the row anyway).
PRIMARY_OVERRIDE = {}
for t in ("ice", "packed_ice", "blue_ice", "powder_snow", "snow", "snow_block"):
    PRIMARY_OVERRIDE["minecraft:" + t] = "Snowy"
for t in ("mycelium", "red_mushroom_block", "brown_mushroom_block", "mushroom_stem"):
    PRIMARY_OVERRIDE["minecraft:" + t] = "Mushroom Fields"
PRIMARY_OVERRIDE["minecraft:bowl"] = "Fishing"
PRIMARY_OVERRIDE["minecraft:cocoa_beans"] = "Jungle"

# Obtainable only by an interaction with no loot table of its own.
MANUAL = {}
for w in ("oak", "spruce", "birch", "jungle", "acacia", "dark_oak", "mangrove", "cherry", "pale_oak"):
    MANUAL["minecraft:stripped_%s_log" % w] = ("Wood", "use an axe on a %s log" % w)
    MANUAL["minecraft:stripped_%s_wood" % w] = ("Wood", "use an axe on %s wood" % w)
for w in ("crimson", "warped"):
    MANUAL["minecraft:stripped_%s_stem" % w] = ("Wood", "use an axe on a %s stem" % w)
    MANUAL["minecraft:stripped_%s_hyphae" % w] = ("Wood", "use an axe on %s hyphae" % w)
MANUAL.update({
    "minecraft:stripped_bamboo_block": ("Wood", "use an axe on a bamboo block"),
    "minecraft:dragon_egg": ("End", "ender dragon's first death; move with a piston"),
    "minecraft:dragon_head": ("End", "mine from the end ship's bow"),
    "minecraft:wither_rose": ("Overworld (other)", "a wither kills a mob"),
    "minecraft:player_head": ("Overworld (other)", "a charged creeper kills a player"),
    "minecraft:beetroot": ("Overworld (other)", "grow beetroot seeds"),
    "minecraft:torchflower": ("Overworld (other)", "grow torchflower seeds (sniffer)"),
    "minecraft:pitcher_plant": ("Overworld (other)", "grow a pitcher pod (sniffer)"),
    # Verified to appear in ZERO loot tables: the elytra is item-frame entity data inside the
    # end ship template, and the nether star is a hardcoded wither drop.
    "minecraft:elytra": ("End", "take from the item frame on an end ship"),
    "minecraft:nether_star": ("Nether", "kill the wither"),
    "minecraft:dragon_breath": ("End", "bottle the ender dragon's breath cloud"),
    # Bucket fills - an interaction, so no loot table names them.
    "minecraft:lava_bucket": ("Cave & Underground", "fill a bucket from lava"),
    "minecraft:powder_snow_bucket": ("Snowy", "fill a bucket from powder snow"),
    "minecraft:salmon_bucket": ("River", "bucket a salmon"),
    "minecraft:axolotl_bucket": ("Cave & Underground", "bucket an axolotl (lush caves)"),
    "minecraft:tadpole_bucket": ("Swamp", "bucket a tadpole"),
    "minecraft:mushroom_stew": ("Mushroom Fields", "milk a mooshroom with a bowl"),
    "minecraft:ominous_banner": ("Structures & Chest Loot", "kill a raid captain"),
})

# Routes the loot data cannot express, appended to rows that already exist.
WHY_EXTRA = {
    "minecraft:trident": "kill a naturally-spawned drowned holding one",
    "minecraft:honey_bottle": "use a glass bottle on a full beehive",
    "minecraft:goat_horn": "a goat rams a hard block",
    "minecraft:water_bucket": "fill a bucket from water",
    "minecraft:milk_bucket": "milk a cow, goat or mooshroom",
    "minecraft:snowball": "shovel a snow layer",
    "minecraft:obsidian": "water meets a lava source",
    "minecraft:cobblestone": "water meets flowing lava",
    "minecraft:clay_ball": "pointed dripstone drips onto mud",
    "minecraft:sculk": "a sculk catalyst consumes a mob death",
}

WOOD_SUFF = ("_log", "_wood", "_leaves", "_sapling", "_planks", "_stem", "_hyphae", "_propagule")


def is_wood(i):
    s = i.replace("minecraft:", "")
    if s.endswith("_stem") and s in ("melon_stem", "pumpkin_stem"):
        return False
    return s.endswith(WOOD_SUFF) or s in ("bamboo", "stripped_bamboo_block", "bamboo_block", "stick")


UNDER = {"minecraft:" + x for x in
         ["raw_iron", "raw_copper", "raw_gold", "coal", "diamond", "emerald", "lapis_lazuli", "redstone",
          "amethyst_shard", "echo_shard", "sculk", "sculk_catalyst", "sculk_sensor", "sculk_shrieker",
          "sculk_vein", "pointed_dripstone", "dripstone_block", "clay_ball", "deepslate", "tuff",
          "calcite", "andesite", "diorite", "granite", "cobblestone", "stone", "glow_berries",
          "spore_blossom", "big_dripleaf", "small_dripleaf", "hanging_roots", "rooted_dirt", "moss_block",
          "amethyst_block", "obsidian", "cobbled_deepslate", "gravel", "flint", "budding_amethyst",
          "smooth_basalt", "moss_carpet", "azalea", "flowering_azalea", "glow_lichen", "cobweb"]}
for t in ("coal", "iron", "copper", "gold", "redstone", "emerald", "lapis", "diamond"):
    UNDER |= {"minecraft:%s_ore" % t, "minecraft:deepslate_%s_ore" % t}

HOW = {"gameplay/piglin_bartering": "piglin bartering", "gameplay/cat_morning_gift": "cat morning gift",
       "gameplay/sniffer_digging": "sniffer digging", "gameplay/panda_sneeze": "panda sneeze",
       "gameplay/armadillo_shed": "armadillo shed", "gameplay/turtle_grow": "turtle grows up",
       "gameplay/chicken_lay": "chicken lays egg", "carve/pumpkin": "shear a pumpkin",
       "brush/armadillo": "brush an armadillo", "pots/trial_chambers/corridor": "decorated pot"}

keep, dropped = {}, []
for item, paths in src.items():
    # Evidence tiers: natural generation is stronger evidence of "where this comes from"
    # than a mob that wanders, which is stronger than a block sitting in a structure.
    T = {1: set(), 2: set(), 3: set(), 4: set(), 5: set()}
    why = []
    for p in paths:
        if p.startswith("blocks/"):
            b = "minecraft:" + p.split("/", 1)[1]
            if b in WORLDGEN:
                tier = 1 if b in NATURAL else 3
                T[tier] |= blk_dom.get(b, {"Overworld (other)"})
                why.append("mine " + p.split("/", 1)[1])
        elif p.startswith("entities/"):
            nm = p.split("/", 1)[1]
            base = nm.split("/")[0]
            got = mob_dom.get("minecraft:" + base, set())
            if not got:
                fb = MOB_FALLBACK.get(base)
                if fb:
                    got = {fb}
            T[2] |= got
            why.append("kill " + base)
        elif p.startswith("chests/"):
            n = p.split("/", 1)[1]
            if any(k in n for k in ("nether", "bastion", "ruined_portal")):
                T[3].add("Nether")
            elif "end_city" in n:
                T[3].add("End")
            elif any(k in n for k in ("shipwreck", "buried_treasure", "underwater", "ocean_ruin")):
                T[3].add("Ocean")
            else:
                T[3].add("Structures & Chest Loot")
            why.append("chest " + n)
        elif p.startswith("trade/"):
            T[4].add("Trading")
            why.append("trade " + p.split("/", 1)[1].split("/")[0])
        elif p.startswith("archaeology/"):
            T[4].add("Archaeology")
            why.append("brush " + p.split("/", 1)[1])
        elif p.startswith("gameplay/fishing"):
            T[4].add("Fishing")
            why.append("fishing")
        elif p.startswith("gameplay/hero_of_the_village"):
            T[4].add("Trading")
            why.append("hero of the village gift")
        elif p.startswith("shearing/"):
            T[5].add("Overworld (other)")
            why.append("shear " + p.split("/", 1)[1].split("/")[0])
        elif p.startswith("harvest/"):
            T[5].add("Overworld (other)")
            why.append("harvest " + p.split("/", 1)[1])
        elif p.startswith("charged_creeper/"):
            T[5].add("Overworld (other)")
            why.append("charged creeper kills " + p.split("/", 1)[1])
        elif p.startswith(("pots/", "spawners/", "equipment/", "dispensers/")):
            T[3].add("Structures & Chest Loot")
            why.append(HOW.get(p, p.split("/")[0] + " (trial chambers)"))
        elif p in HOW:
            T[5].add("Overworld (other)")
            why.append(HOW[p])
        elif p.startswith("gameplay/"):
            T[5].add("Overworld (other)")
            why.append(p.split("/", 1)[1])
    D = T[1] | T[2] | T[3] | T[4] | T[5]
    best_tier = next((t for t in (1, 2, 3, 4, 5) if T[t]), None)
    best = T[best_tier] if best_tier else set()
    if not D:
        dropped.append(item)
        continue
    if item in PRIMARY_OVERRIDE:
        prim = PRIMARY_OVERRIDE[item]
    elif is_wood(item):
        prim = "Wood"
    elif item in UNDER:
        prim = "Cave & Underground"
    elif len(best & OW_BIOME) >= 3:
        # spans many overworld biomes -> generic, not biome-specific
        prim = "Overworld (other)"
    elif best_tier == 3 and len(best) >= 3:
        # turns up in several unrelated structures -> generic structure loot
        prim = "Structures & Chest Loot"
    elif "Overworld (other)" in best and item in SURFACE_ITEMS:
        # ordinary terrain that also happens to line a cave biome
        prim = "Overworld (other)"
    else:
        prim = next((d for d in DOMS if d in best), "Other")
    # A craftable block whose only appearance is inside a structure's palette is decoration,
    # not a resource: you can mine a fence out of a shipwreck, but that is not where fences
    # come from. Flag it so the checklist can demote it out of the main rows.
    mined = [w[5:] for w in why if w.startswith("mine ")]
    struct_only = (item in craft and len(mined) == len(why) and mined
                   and all("minecraft:" + b not in NATURAL for b in mined))
    keep[item] = {"primary": prim, "domains": sorted(D), "why": sorted(set(why)),
                  "craftable": item in craft, "struct_only": bool(struct_only)}

for item, extra in WHY_EXTRA.items():
    if item in keep and extra not in keep[item]["why"]:
        keep[item]["why"] = sorted(keep[item]["why"] + [extra])

for item, (dom, how) in MANUAL.items():
    if item in keep:
        continue
    keep[item] = {"primary": dom, "domains": [dom], "why": [how], "craftable": item in craft}
    if item in dropped:
        dropped.remove(item)

json.dump(keep, open(SP + "/rows.json", "w"), indent=0)
json.dump(sorted(dropped), open(SP + "/dropped.json", "w"), indent=0)
byd = collections.defaultdict(list)
for i, r in keep.items():
    byd[r["primary"]].append(i)
for d in DOMS:
    if byd.get(d):
        print("%-26s %4d" % (d, len(byd[d])))
print("TOTAL KEPT", len(keep), " DROPPED", len(dropped))
